# Model arguments
model_name_or_path: /scratch/project_462000319/zosaelai2/models/viking_v2_13B_iter_0453000_bfloat16
torch_dtype: bfloat16

# LoRA arguments
# load_in_4bit: true
use_peft: true
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

# Data training arguments
chat_template: "{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"
dataset_mixer:
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/english/instruction-collection-eng: 1.0
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/finnish/instruction-collection-fin: 1.0
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/swedish/instruction-collection-swe: 1.0
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/danish/instruction-collection-opus: 1.0
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/icelandic/instruction-collection-nllb: 1.0
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/norwegian/instruction-collection-nob-nllb: 1.0
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/cross-lingual/FLORES-101/translation: 1.0
  # /scratch/project_462000319/finetuning_data/SFTTrainer_format/cross-lingual/FLORES-101/lang_identification: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 1

# SFT trainer config
bf16: true
do_eval: true
evaluation_strategy: epoch
# eval_steps: 1000
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 2.0e-04
log_level: info
logging_steps: 20  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 3
output_dir: data/viking-13b-lora-instruction-collection-all-ckpt-0453000-rope-fix
# overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
remove_unused_columns: true
save_strategy: "epoch"
#save_steps: 500
save_total_limit: 1
seed: 42
warmup_ratio: 0.1