# Model arguments
model_name_or_path: /scratch/project_462000319/general-tools/viking_v2_checkpoints/viking_v2_7B_iter_0476837_bfloat16
# model_revision: main
torch_dtype: bfloat16

# Data training arguments
dataset_mixer:
  /scratch/project_462000319/finetuning_data/mmlu-formatted: 1.0
dataset_splits:
  - train
  - test
preprocessing_num_workers: 1

# SFT trainer config
bf16: true
do_eval: True
evaluation_strategy: steps
eval_steps: 50
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
# hub_model_id: gpt2-cpt-dutch
# hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 20  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 1024
max_steps: -1
num_train_epochs: 3
output_dir: data/viking-cpt-mmlu-no-packing-3epochs
# overwrite_output_dir: true
per_device_eval_batch_size: 8
per_device_train_batch_size: 4
# push_to_hub: true
remove_unused_columns: true
# report_to:
# - wandb
save_strategy: "epoch"
#save_steps: 100
save_total_limit: 3
seed: 42
warmup_ratio: 0.1
