# Model arguments
model_name_or_path: /scratch/project_462000444/zosaelai2/models/poro-mixed-poro-full-extended-cleaned-batch48
torch_dtype: bfloat16

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  /scratch/project_462000444/finetuning_data/DPOTrainer_format/english/nvidia/HelpSteer2: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 1

# DPOTrainer arguments
bf16: true
beta: 0.05
do_eval: true
evaluation_strategy: epoch
# eval_steps: 100
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 5.0e-7
log_level: info
logging_steps: 20
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 5
optim: adamw_torch
output_dir: data/poro-chat-dpo-full-helpsteer2-lr-5e-6-epoch-5-batch-32 
per_device_train_batch_size: 1
per_device_eval_batch_size: 4
save_strategy: "epoch"
save_total_limit: 1
seed: 42
warmup_ratio: 0.1