# Model arguments
model_name_or_path: /scratch/project_462000319/zosaelai2/zephyr-reproduce/alignment-handbook-2/alignment-handbook/data/merged-poro-dolly-oasst-lima-glaive_eng-fin-step2400
torch_dtype: auto

# LoRA arguments
use_peft: true
# load_in_4bit: true
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- query_key_value
- dense
- dense_4h_to_h
- dense_h_to_4h
- lm_head

# Data training arguments

dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.01
do_eval: true
evaluation_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
# hub_model_id: zephyr-7b-dpo-qlora
learning_rate: 8.0e-6
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 1024
max_prompt_length: 512
num_train_epochs: 2
optim: adamw_torch
output_dir: data/poro-dpo-dolly-oasst-lima-glaive_eng-fin-step2400-qlora # It is handy to append `hub_model_revision` to keep track of your local experiments
per_device_train_batch_size: 4
per_device_eval_batch_size: 8
# push_to_hub: true
save_strategy: "steps"
save_steps: 100
save_total_limit: 5
seed: 42
warmup_ratio: 0.1