# Model arguments
model_name_or_path: /scratch/project_462000444/zosaelai2/models/viking_v2_33B_iter_0358000_bfloat16
torch_dtype: bfloat16

# LoRA arguments
# load_in_4bit: true
use_peft: true
lora_r: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

# Data training arguments
chat_template: "{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"
dataset_mixer:
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/english/instruction-collection-eng: 1.0
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/finnish/instruction-collection-fin: 1.0
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/swedish/instruction-collection-swe: 1.0
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/danish/instruction-collection-opus: 1.0
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/icelandic/instruction-collection-nllb: 1.0
  /scratch/project_462000319/finetuning_data/SFTTrainer_format/norwegian/instruction-collection-nob-nllb: 1.0
  # /scratch/project_462000319/finetuning_data/SFTTrainer_format/cross-lingual/FLORES-101/translation: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 1

# SFT trainer config
bf16: true
do_eval: false
evaluation_strategy: epoch
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.0e-04
log_level: info
logging_steps: 10  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 3
output_dir: data/viking-33b-lora-instruction-collection-all-ckpt-0358000
# overwrite_output_dir: true
per_device_eval_batch_size: 8
per_device_train_batch_size: 4
save_strategy: "epoch"
# save_steps: 100
save_total_limit: 1
seed: 42
warmup_ratio: 0.1